FROM node:18.16-alpine as builder

WORKDIR /app

COPY package*.json /app/

RUN npm ci

COPY . .

FROM builder as app

COPY --from=builder /app/dist /app/dist/

COPY package.json /app/

RUN npm run build

ENV NODE_ENV production

RUN npm link
