apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 1536Mi
    - name: node
      image: node:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 1536Mi
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock