apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: octommit-publish
  namespace: argo
  generateName: octommit-publish-
spec:
  imagePullSecrets:
    - name: dockerhub
  ttlStrategy:
    secondsAfterCompletion: 300
  securityContext:
    fsGroup: 2000 
  serviceAccountName: argo
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi    
  arguments:
    parameters:
      - name: branch
        value: main
  entrypoint: octommit-build
  templates:
  - name: octommit-build
    steps:
    - - name: checkout
        templateRef:
          name: git
          template: checkout
        arguments:
          parameters:
          - name: branch
            value: "{{workflow.parameters.branch}}"
          - name: repository
            value: "octommit"
    - - name: build-packages
        template: build-package
        arguments:
          parameters:
            - name: package
              value: "{{item}}"
        withItems: 
          - core
          - cli
          - connector
    - - name: semver
        templateRef:
          name: semantic-version
          template: version
        arguments:
          parameters:
          - name: repository
            value: octommit
          - name: branches
            value: "--branches main"
    - - name: get-tag
        templateRef:
          name: git
          template: get-tag
        arguments:
          parameters:
          - name: repository
            value: octommit
      - name: update-readme
        template: update-readme
    - - name: publish-core
        template: publish
        arguments:
          parameters:
            - name: package
              value: "core"
            - name: version
              value: "{{steps.get-tag.outputs.parameters.tag}}"
        withItems: 
          - core
          - connector
          - cli
    - - name: publish-packages
        template: publish
        arguments:
          parameters:
            - name: package
              value: "{{item}}"
            - name: version
              value: "{{steps.get-tag.outputs.parameters.tag}}"
        withItems: 
          - connector
          - cli
        when: "{{steps.get-tag.outputs.result}} == true"
    - - name: docker-build-and-push
        templateRef:
          name: docker
          template: build-and-push
        arguments:
          parameters:
          - name: repository
            value: octommit
          - name: tag
            value: "{{steps.get-tag.outputs.parameters.tag}}"
          - name: buildArgs
            value: "--build-arg NPM_TOKEN=$(NPM_TOKEN)"
        when: "{{steps.get-tag.outputs.result}} == true"

  - name: build-package
    inputs:
      parameters:
        - name: package
    steps:
      - - name: build
          templateRef:
            name: npm
            template: run
          arguments:
            parameters:
            - name: repository
              value: "octommit/packages/{{inputs.parameters.package}}"
            - name: script
              value: |
                npm install
                npm run build
      - - name: test
          templateRef:
            name: npm
            template: run
          arguments:
            parameters:
            - name: repository
              value: "octommit/packages/{{inputs.parameters.package}}"
            - name: script
              value: |-
                npm run test -- --coverage;

  - name: publish
    inputs:
      parameters:
        - name: package
        - name: version
    steps:
      - - name: npm-publish
          templateRef:
            name: npm
            template: run
          arguments:
            parameters:
            - name: repository
              value: "octommit/packages/{{inputs.parameters.package}}"
            - name: script
              value: |-
                npm version {{inputs.parameters.version}}
                npm publish --registry https://verdaccio.stocko-infra.net;
  - name: update-readme
    steps:
      - - name: git-sync
          templateRef:
            name: git
            template: run
          arguments:
            parameters:
              - name: repository
                value: "octommit"
              - name: script
                value: |-
                  git pull
      - - name: update-readme
          templateRef:
            name: npm
            template: run
          arguments:
            parameters:
            - name: repository
              value: "octommit/packages/{{item}}"
            - name: script
              value: |-
                npm run make:badges
          withItems:
            - core
            - connector
            - cli
      - - name: commit-readme
          templateRef:
            name: git
            template: run
          arguments:
            parameters:
              - name: repository
                value: "octommit"
              - name: script
                value: |-
                  git add README.md;
                  git commit -m "docs(ci): update readme [skip ci]";
                  git push