replicaCount: 1

image:
  repository: stockopedia/directory-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: 
  - name: dockerhub

namespace: app
nameOverride: "directory-service"
fullnameOverride: "directory-service"

env:
  - configMapRef:
      name: directory-service-config
  - secretRef:
      name: directory-service-secrets

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1536Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
